# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31aca5ad0b2f300f7d7fdd1f847fdcb9e546680d2dbda212699ca9b0f4bfbb13d0b8641a577ca59c5b331aecddaa26dc58db86d9ad565eeca08b75c2b18236c4

test:
  secret_key_base: d830c5bc996de1f665835dbab9f76d6064f93c4b3311807dd516c6d004a6525baed613fde3c268396db042baaf72c5648e376646f7219d7f5df15f653a2ea00d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
